name: Ejercicio 1

on:
  push:
    branches: [ main ]

jobs:
  hello:    
    runs-on: ubuntu-latest  
    
    steps:
      - name: Imprimir nombre
        run: echo "Hola, mi nombre es Cristhian J. Paz"
      
      - name: Imprimir fecha y hora
        run: date
      
      - name: Imprimir sistema operativo
        run: echo "Sistema operativo: ${{ runner.os }}"